# @package _global_
path:
  experiments_path: ./experiments/experiments_db/
  logging_path: ./experiments/
  checkpoint_path: null
  model_path: /scratch/y/ycc888/models--meta-llama--Llama-3.3-70B-Instruct/snapshots/6f6073b423013f6a7d4d9f39144961bfbfbc386b 
  model_name: llama-3-70b
